name: Build and Push Docker Image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Docker tag"
        required: true
        type: choice
        options:
          - latest
          - dev
  push:
    branches: [ "master" ]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Docker tag
        id: vars
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "tag=${{ inputs.tag }}" >> "$GITHUB_OUTPUT"
          else
            echo "tag=latest" >> "$GITHUB_OUTPUT"
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Dockge base image
        run: |
          docker build . \
            --file docker/Base.Dockerfile \
            --tag cmcooper1980/dockge:base

      - name: Build Dockge healthcheck image
        run: |
          docker build . \
            --file docker/BuildHealthCheck.Dockerfile \
            --tag cmcooper1980/dockge:build-healthcheck

      - name: Build Docker image
        run: |
          docker build . \
            --file docker/Dockerfile \
            --target release \
            --tag ghcr.io/${{ github.repository_owner }}/dockge:${{ steps.vars.outputs.tag }} \
            --tag ghcr.io/${{ github.repository_owner }}/dockge:${{ github.sha }} \
            --tag ${{ secrets.DOCKERHUB_USERNAME }}/dockge:${{ steps.vars.outputs.tag }} \
            --tag ${{ secrets.DOCKERHUB_USERNAME }}/dockge:${{ github.sha }}

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/dockge:${{ steps.vars.outputs.tag }}
          docker push ghcr.io/${{ github.repository_owner }}/dockge:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/dockge:${{ steps.vars.outputs.tag }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/dockge:${{ github.sha }}
